---
- hosts: test
  vars:
     Build: cat /var/lib/jenkins/jobs/EYCDJOB/nextBuildNumber
  tasks: 
        - name: deploy inti esk cluster
          command: helm upgrade --install ey-app /var/lib/jenkins/workspace/EYCDJOB/petclinic --set image.repository=rajat6969/eycloud  --set image.tag='{{Build}}'
